#!/bin/bash -eu

set -a $(echo ${1} | tr '/' ' ')

if [[ $# == 2  ]]; then
  GITHUB_USER=${1}
  REPOSITORY_NAME=${2}
  GITHUB_REPOS_API_URL="${GITHUB_API_URL}/orgs/${GITHUB_USER}/repos"
else
  REPOSITORY_NAME=${1}
  GITHUB_REPOS_API_URL="${GITHUB_API_URL}/user/repos"
fi

# API reference is here https://developer.github.com/v3/repos/#create
ghq get $(curl -H "Authorization: token ${GITHUB_TOKEN}" ${GITHUB_REPOS_API_URL} -d '{"name": "'${REPOSITORY_NAME}'", "auto_init": "true"}' -s | jq -r '.ssh_url')
echo $(ghq root)/${GITHUB_HOST}/${GITHUB_USER}/${REPOSITORY_NAME}

# cd $(ghq root)/${GITHUB_HOST}/${GITHUB_USER}/${REPOSITORY_NAME}
# exec $SHELL -l
