#!/bin/bash -eu

GITHUB_REPOS_API_URL="${GITHUB_API_URL}/user/repos"

set -a $(echo ${1} | tr '/' ' ')

if [[ $# == 2  ]]; then
  GITHUB_USER=${1}
  REPOSITORY_NAME=${2}
else
  REPOSITORY_NAME=${1}
fi

ghq get $(curl -H "Authorization: token ${GITHUB_TOKEN}" ${GITHUB_REPOS_API_URL} -d '{"name": "'${REPOSITORY_NAME}'"}' -s | jq -r '.ssh_url')
echo $(ghq root)/${GITHUB_HOST}/${GITHUB_USER}/${REPOSITORY_NAME}

# cd $(ghq root)/${GITHUB_HOST}/${GITHUB_USER}/${REPOSITORY_NAME}
# exec $SHELL -l
